Repository rust-lang/rustc_codegen_cranelift, pull requests merged in 2022-08, with the labels that each got.

#1260 Ignore ptr_bitops_tagging test on s390x
  patches/0023-sysroot-Ignore-failing-tests.patch
Labels: O-SystemZ

#1264 Refactorings for enabling parallel compilation (part 1)
  Readme.md
  example/mini_core_hello_world.rs
  src/base.rs
  src/driver/aot.rs
  src/driver/jit.rs
  src/global_asm.rs
  src/lib.rs
  src/toolchain.rs
Labels: C-enhancement, compile-time

#1266 Refactorings for enabling parallel compilation (part 2)
  src/base.rs
  src/common.rs
  src/debuginfo/emit.rs
  src/debuginfo/line_info.rs
  src/debuginfo/mod.rs
  src/driver/aot.rs
  src/driver/jit.rs
  src/lib.rs
  src/optimize/mod.rs
  src/pretty_clif.rs
Labels: C-enhancement, compile-time, C-cleanup

#1271 Support compiling codegen units in parallel
  src/base.rs
  src/common.rs
  src/concurrency_limiter.rs
  src/driver/aot.rs
  src/lib.rs
Labels: C-enhancement, compile-time

#1273 Use pull instead of push based model for getting dylib symbols in the jit
  build_system/tests.rs
  src/driver/jit.rs
Labels: O-windows, A-jit
